---
BS1:
  serial_no: '127.0.0.1:5565'
  troop_slot: 3
  wall_repair: False
  super_mine_gathering: False
  resource_type: ['wood']
  default_tribute_collect_interval: 600

BS2:
  serial_no: '127.0.0.1:5575'
  troop_slot: 3
  wall_repair: False
  super_mine_gathering: False
  resource_type: ['wood']
  default_tribute_collect_interval: 600

BS3:
  serial_no: '127.0.0.1:5585'
  troop_slot: 3
  wall_repair: False
  super_mine_gathering: False
  resource_type: ['food']
  default_tribute_collect_interval: 600
...
